### ISSUE TITLE
How do I disable the clear button from showing up?

### ISSUE THREAD

**Issue by posix4e** [urbanstems/react-geosuggest-plus#3]
I get this ugly blue box, i want to hide the button

**Comment by dustinws** [comment]
Hi @posix4e, thanks for reaching out. Currently there isn't an option to disable the clear button.

However this would be a pretty quick / easy addition. @cshenoy Do you have any thoughts?

**Comment by posix4e** [comment]
I'm confused as in the example it doesn't show up

**Comment by dustinws** [comment]
@posix4e The example could be stale, I'll double check and make sure everything is up to date. Thanks for pointing that out!

As for disabling the 'clear' button, those changes should now be live in v1.2.1.

There is a new optional prop called `hideClearButton` that can accept a boolean.
This is mentioned in the docs now as well.

I hope this helps!
